version: "3"

services:
  write-api:
    image: go-social/write-api
    container_name: go-social-write-api
    build:
      context: ./activity-write-api
    depends_on:
      - rabbitmq-server
      - mongo-server
    environment:
      "WRITE_MQ_MASTER_CONN_STR": "amqp://test:password@localhost:5672/" # For the sake of testing
      "WRITE_MQ_SLAVE_CONN_STR": "amqp://test:password@localhost:5672/" # Master and slave are identical
      "WRITE_API_QUEUE_NAME": "activity-write-queue"
    ports:
      - "8080:8080"
    links:
      - rabbitmq-server
  rabbitmq-server:
    image: go-social/mqserver
    container_name: go-social-topic-mq
    build:
      context: ./mqserver
    environment:
      "RABBITMQ_USER": "test"
      "RABBITMQ_PASS": "password"
      "WRITE_API_QUEUE_NAME": "activity-write-queue"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./mqserver/data:/var/lib/rabbitmq
  mongo-server:
    image: go-social/mongo
    container_name: go-social-mongo
    build:
      context: ./mongoserver
    ports:
      - "27018:27017"
    environment:
      "MONGO_INITDB_ROOT_USERNAME": "root"
      "MONGO_INITDB_ROOT_PASSWORD": "example"
      "PROJECTION_MAIN_NAME": "go-social-db"
      "PROJECTION_SLAVE_NAME": "go-social-slave"
    volumes:
      - ./mongoserver/data:/data/db
      - ./mongoserver/bk:/data/bkp
    restart: always
