version: "3"

services:
  write.api:
    image: go-social/write-api
    container_name: go-social-write-api
    build:
      context: ./activity-write-api
    depends_on:
      - rabbitmqserver
      - write.daemon
    environment:
      "WRITE_MQ_MASTER_CONN_STR": "amqp://test:password@rabbitmqserver:5672/" # For the sake of testing
      "WRITE_MQ_SLAVE_CONN_STR": "amqp://test:password@rabbitmqserver:5672/" # Master and slave are identical
      "WRITE_API_QUEUE_NAME": "activity-write-queue"
    ports:
      - "8080:8080"
    links:
      - rabbitmqserver
  write.daemon:
    image: go-social/write-daemon
    container_name: go-social-write-daemon
    build:
      context: ./activity-write-daemon
    depends_on:
      - rabbitmqserver
      - pgserver
    environment:
      "WRITE_MQ_CONN_STR": "amqp://test:password@rabbitmqserver:5672/" # For local testing only
      "WRITE_API_QUEUE_NAME": "activity-write-queue"
      "EVENT_STORE_STR": "host=pgserver port=5432 user=dev01 dbname=gosocialdb password=godevrocks sslmode=disable"
      "READ_MQ_CONN_STR": "amqp://test:password@rabbitmqserver:5672/" # For local testing only
      "READ_MQ_SLAVE_CONN_STR": "amqp://test:password@rabbitmqserver:5672/" # For local testing only
      "ACTIVITY_EXCHANGE_NAME": "activity-topic-exchange"
    links:
      - rabbitmqserver
      - pgserver
  my.feed.daemon:
    image: go-social/my-feed-daemon
    container_name: go-social-my-feed-daemon
    build:
      context: ./my-feed-daemon
    depends_on:
      - rabbitmqserver
      - mongoserver
    environment:
      "READ_MQ_CONN_STR": "amqp://test:password@rabbitmqserver:5672/" # For local testing only
      "MY_FEED_PROJECTOR_QUEUE_NAME": "my-feed-queue"
    links:
      - rabbitmqserver
      - mongoserver
  friends.feed.daemon:
    image: go-social/friends-feed-daemon
    container_name: go-social-friends-feed-daemon
    build:
      context: ./friends-feed-daemon
    depends_on:
      - rabbitmqserver
      - mongoserver
    environment:
      "READ_MQ_CONN_STR": "amqp://test:password@rabbitmqserver:5672/" # For local testing only
      "FRIENDS_FEED_PROJECTOR_QUEUE_NAME": "friends-feed-queue"
    links:
      - rabbitmqserver
      - mongoserver
  rabbitmqserver:
    image: go-social/mqserver
    container_name: go-social-topic-mq
    hostname: rabbitmqserver
    build:
      context: ./mqserver
    environment:
      "RABBITMQ_USER": "test"
      "RABBITMQ_PASS": "password"
      "WRITE_API_QUEUE_NAME": "activity-write-queue"
      "MY_FEED_PROJECTOR_QUEUE_NAME": "my-feed-queue"
      "FRIENDS_FEED_PROJECTOR_QUEUE_NAME": "friends-feed-queue"
      "ACTIVITY_EXCHANGE_NAME": "activity-topic-exchange"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./mqserver/data:/var/lib/rabbitmq
  mongoserver:
    image: go-social/mongo
    container_name: go-social-mongo
    hostname: mongoserver
    build:
      context: ./mongoserver
    ports:
      - "27018:27017"
    environment:
      "MONGO_INITDB_ROOT_USERNAME": "root"
      "MONGO_INITDB_ROOT_PASSWORD": "example"
      "PROJECTION_MAIN_NAME": "go-social-db"
      "PROJECTION_SLAVE_NAME": "go-social-slave"
    volumes:
      - ./mongoserver/data:/data/db
      - ./mongoserver/bk:/data/bkp
    restart: always
  pgserver:
    image: postgres
    container_name: go-social-es-store
    hostname: pgserver
    restart: always
    environment:
      POSTGRES_PASSWORD: godevrocks
      POSTGRES_USER: dev01
      POSTGRES_DB: gosocialdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgserver/postgres-data:/var/lib/postgresql/data
      - ./pgserver/001_tables:/go-social/sql/001_tables
      - ./pgserver/002_data:/go-social/sql/002_data
      - ./pgserver/boot.sh:/docker-entrypoint-initdb.d/boot.sh
